name: Publish Package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        # pnpm: [8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-setup
        with:
          node-version: ${{ matrix.node }}
      - name: Build Lib
        run: pnpm build:lib
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kissmannchristoph/vuetify-pro-tiptap'
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
