name: Publish Package
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
        # pnpm: [8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-setup
        with:
          node-version: ${{ matrix.node }}
      - name: Build Lib
        run: pnpm build:lib
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: https://npm.pkg.github.com/
          NPM_CONFIG_PROVENANCE: true
        run: pnpm semantic-release
